spring:
  application:
    name: netteca
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://localhost:5432/netteca
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    defer-datasource-initialization: true
security:
  jwt:
    secret: bdx8W1lOwFSZQjQlMqGnvVe1OeC2k1Epgn9mnQMAW1eLu04dqrla72NTyJ70-vNP
    expiration-ms: 900000

server:
  port: 8080
  servlet:
    context-path: /netteca

